### PR TITLE
Possible Fix for "Nonce must be incremented"

### PR DESCRIPTION
**Pull request by kingchenc**
Hope this fix work now for the error -> Nonce must be incremented

### CODE REVIEW

**Comment by kingchenc** [comment]
Nope, this bugfix dont fix the nonce error :/ any ideas @JordanJones ??

**Comment by jordansjones** [comment]
@kingchenc Are you making calls in parallel?

**Comment by kingchenc** [comment]
@jordansjones Yes im running in tasks parallel

**Comment by jordansjones** [comment]
@kingchenc when running tasks in parallel you run the risk of having a request with a higher nonce being processed on the server before a request with a lower nonce.

I believe the issues isn't in the Nonce.cs code, but in the coordination of your parallel api calls. If you still get this error running the calls sequentially, then let me know and I'll dig in and see what I can get figured out.

**Comment by jordansjones** [comment]
@kingchenc I am going to close this as I don't believe the issue you are encountering is related to this library.

Please feel free to re-open if I am wrong.

**Pull request closed without merging**
